apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: go-micro
      imagePullSecrets:
      - name: harbor-cred
      containers:
        - name: server
          image: harbor.creativebox.dev/micro/shippingservice:latest
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: TRACING_ENABLE
              value: "true"
            - name: TRACING_JAEGER_URL
              value: "http://jaeger-collector.default.svc.cluster.local:14268/api/traces"
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
